<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FundingApi</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
  </PropertyGroup>
	<PropertyGroup>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
		<UserSecretsId>2e687ee8-3b13-4bde-b38f-80173a7d9cbe</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="healthchecksdb" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.CosmosDb" Version="9.0.0" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.22" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.50.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.79.2" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="8.0.22" />
    <PackageReference Include="Pds.Core.ApiAuthentication" Version="2.0.1" />
    <PackageReference Include="Pds.Core.CodeAnalysis.StyleCop" Version="2.0.0" />
    <PackageReference Include="Pds.Core.Telemetry.ApplicationInsights" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\PDS.ViewYourFunding.Data.Core.csproj" />
    <ProjectReference Include="..\Interfaces\PDS.ViewYourFunding.Data.Interfaces.csproj" />
    <ProjectReference Include="..\PDS.VYF.Data.Services\PDS.VYF.Data.Services.csproj" />
    <ProjectReference Include="..\Services\PDS.ViewYourFunding.Data.Services.csproj" />
  </ItemGroup>

</Project>
